language: node_js
sudo: false
node_js:
    - '0.12'
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm config set spin false
  - npm install -g gulp bower
before_script:
  - npm install
script:
  - gulp test:js